server:
  port: 8080


logging:
  level:
    root: info
    org.springframework.web: info
  file: ./log/log-tool.log
  #pattern:
      #file: [tool] %d %-5p [%t] %c | %m%n
      #console: [tool] %d %-5p [%t] %c | %m%n


spring:
  thymeleaf:
    cache: false
    encoding: utf-8
    prefix: classpath:/templates/
    suffix: .html
    content-type: text/html
    mode: LEGACYHTML5
  http:
    multipart:
      max-file-size: 50Mb
      max-request-size: 50Mb

  #mvc:
    #view:
      #prefix:
      #suffix: